vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       dishes_images:
           uri_prefix: /images/dishes
           upload_destination: '%kernel.project_dir%/public/images/dishes'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
