<?php

namespace ContainerDpbyIer;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MryMuMuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mryMuMu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mryMuMu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'openingHoursRepository' => ['privates', 'App\\Repository\\OpeningHoursRepository', 'getOpeningHoursRepositoryService', true],
            'reservationRepository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
        ], [
            'openingHoursRepository' => 'App\\Repository\\OpeningHoursRepository',
            'reservationRepository' => 'App\\Repository\\ReservationRepository',
        ]);
    }
}
