app_home:
  path: /
  controller: App\Controller\HomeController::index

admin:
  path: /admin
  controller: App\Controller\Admin\DashboardCrudController::index

app_category:
  path: /category
  controller: App\Controller\CategoryController::index

app_contact:
  path: /contact
  controller: App\Controller\ContactController::index

app_dish:
  path: /dish
  controller: App\Controller\DishController::index

app_gallery:
  path: /gallery
  controller: App\Controller\GalleryController::index

app_menu:
  path: /menu
  controller: App\Controller\MenuController::index

app_registration:
  path: /registration
  controller: App\Controller\RegistrationController::index

app_reservation:
  path: /reservation
  controller: App\Controller\ReservationController::index

app_reservation_success:
  path: /reservation/success
  controller: App\Controller\Reservation_successController::index

app_login:
  path: /login
  controller: App\Controller\SecurityController::login

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

