<?php

namespace ContainerSQtoJxR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UBBDOF3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UBBDOF3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UBBDOF3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'menuRepository' => ['privates', 'App\\Repository\\MenuRepository', 'getMenuRepositoryService', true],
            'openingHoursRepository' => ['privates', 'App\\Repository\\OpeningHoursRepository', 'getOpeningHoursRepositoryService', true],
        ], [
            'menuRepository' => 'App\\Repository\\MenuRepository',
            'openingHoursRepository' => 'App\\Repository\\OpeningHoursRepository',
        ]);
    }
}
