<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2VQFykI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2VQFykI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2VQFykI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2VQFykI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2VQFykI\App_KernelDevDebugContainer([
    'container.build_hash' => '2VQFykI',
    'container.build_id' => '1dedf00c',
    'container.build_time' => 1681234312,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2VQFykI');
