<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6l3LPjr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6l3LPjr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6l3LPjr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6l3LPjr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6l3LPjr\App_KernelDevDebugContainer([
    'container.build_hash' => '6l3LPjr',
    'container.build_id' => 'dd1293c1',
    'container.build_time' => 1680775907,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6l3LPjr');
