<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.c09b021f.js',
                '/build/138.dd88dea6.js',
                '/build/app.21596010.js',
            ],
            'css' => [
                '/build/app.b06068fc.css',
            ],
        ],
    ],
],

]];
