<?php

namespace ContainerO7YV7dU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9h5qdI5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9h5qdI5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9h5qdI5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'openingHoursRepository' => ['privates', 'App\\Repository\\OpeningHoursRepository', 'getOpeningHoursRepositoryService', true],
            'reservation' => ['privates', '.errored..service_locator.9h5qdI5.App\\Entity\\Reservation', NULL, 'Cannot autowire service ".service_locator.9h5qdI5": it references class "App\\Entity\\Reservation" but no such service exists.'],
        ], [
            'openingHoursRepository' => 'App\\Repository\\OpeningHoursRepository',
            'reservation' => 'App\\Entity\\Reservation',
        ]);
    }
}
